In [1]:
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np
from open3d import *
import pandas as pd

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [13]:
mesh = o3d.io.read_point_cloud("kota_circuit2.ply")

In [14]:
data = np.asarray(mesh.normals)
point = np.asarray(mesh.points)
color = np.asarray(mesh.colors)

In [15]:
df = pd.DataFrame({'x':point[:,0],'y':point[:,1],'z':point[:,2], 'nx':data[:,0],'ny':data[:,1], \
                   'nz':data[:,2],'red':color[:,0] ,'green':color[:,1],'blue':color[:,2]})

In [16]:
df #  z>=.9, -0.2<x<+0.2, -0.2<y<+0.2

,x,y,z,nx,ny,nz,red,green,blue
0,82.0793,-147.1890,-78.1590,0.013181,0.060839,0.998061,0.776471,0.776471,0.784314
1,97.6007,149.9880,-53.4935,-0.450365,-0.312475,0.836379,0.631373,0.525490,0.400000
2,70.4971,-229.2400,-78.5418,-0.370208,-0.102291,0.923300,0.517647,0.474510,0.419608
3,-76.0481,-211.3700,-77.7762,-0.251140,-0.348555,0.903016,0.337255,0.298039,0.243137
4,170.8700,-31.3686,-42.1278,-0.732085,0.614825,0.293328,0.243137,0.227451,0.192157
...,...,...,...,...,...,...,...,...,...
14640192,39.0648,-49.5742,-89.2125,-0.016475,0.016662,0.999725,0.419608,0.447059,0.290196
14640193,97.6982,332.7250,-86.5379,-0.417351,0.898358,-0.137007,0.180392,0.247059,0.184314
14640194,26.6478,-36.4941,-89.5965,0.027782,0.137174,0.990157,0.356863,0.329412,0.231373
14640195,-88.4722,49.9168,-75.3975,0.287951,-0.751564,0.593494,0.035294,0.043137,0.039216
14640196,-23.1747,335.2590,-102.5880,0.374595,-0.312594,0.872905,0.192157,0.254902,0.196078

In [17]:
cut_out = df[((-0.005 < df['nx']) & (df['nx'] < 0.005)) & ((-0.02 < df['ny']) & (df['ny'] < 0.02)) & ( df['nz'] > 0.93)]

In [18]:
cut_out

,x,y,z,nx,ny,nz,red,green,blue
137,52.74280,-37.1996,-89.3684,0.003815,-0.004117,0.999984,0.419608,0.435294,0.270588
494,-31.49290,-120.5570,-79.2207,0.003666,-0.000061,0.999993,0.615686,0.666667,0.682353
727,3.95426,12.2885,-90.3515,0.004442,-0.009777,0.999942,0.850980,0.843137,0.850980
826,48.80160,-49.3452,-89.2352,-0.004707,-0.016027,0.999860,0.403922,0.384314,0.243137
1053,-127.08400,-176.4860,-114.7910,-0.001036,0.000551,0.999999,0.752941,0.745098,0.725490
...,...,...,...,...,...,...,...,...,...
14639367,67.68930,-159.2510,-78.2541,0.001879,0.018089,0.999835,0.505882,0.482353,0.525490
14639383,-27.24060,78.8664,-91.5437,-0.000436,0.008086,0.999967,0.996078,1.000000,1.000000
14639439,3.75726,63.8442,-90.9962,-0.004665,0.011266,0.999926,0.592157,0.596078,0.607843
14639612,-37.96370,199.7900,-94.5644,0.000998,-0.013047,0.999914,0.678431,0.674510,0.462745
14639640,176.93000,-98.8369,-41.9024,-0.000357,0.014365,0.999897,0.113725,0.152941,0.223529

In [19]:
pcd = o3d.geometry.PointCloud()

In [20]:
pcd.points = o3d.utility.Vector3dVector(cut_out[['x','y','z']].values)

In [21]:
pcd.normals = o3d.utility.Vector3dVector(cut_out[['nx','ny','nz']].values)

In [22]:
pcd.colors = o3d.utility.Vector3dVector(cut_out[['red','green','blue']].values)

In [23]:
o3d.visualization.draw_geometries([pcd])